name: Build check
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  macos_build_job:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15, macos-14]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup tools
        run: brew install soapysdr libftdi
      - name: Configure
        run: cmake -B build
      - name: Build
        run: cmake --build build

  linux_build_job:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup tools
        run: |
          sudo apt-get update -q -y
          sudo apt-get install -y --no-install-recommends cmake ninja-build
          sudo apt-get install -q -y libsoapysdr-dev libftdi-dev libftdi-dev
          libftdi-config --libs --cflags
      - name: Configure
        run: cmake -GNinja -B build
      - name: Build
        run: cmake --build build
